#+title: ANDB
#+subtitle: Werk repository voor de ANDB dataset in linked data

* Wat is de ANDB?

De Algemene Nederlandse Diamantbewerkers Bond is een historische
dataset waarin mensen die in de diamantbewerkers sector gewerkt hebben
zijn opgeslagen.  Deze dataset wordt gebruikt in verschillende
historische onderzoeken.

* Waarom linked data?

Linked data is een methode waarmee ingewikkelde gegevens op een
betekenisvolle manier kunnen worden ontsloten.

* Voor wie is dit repository bedoeld?

Dit repository is bedoeld voor ontwikkelaars die aan de ANDB dataset
werken.  Gebruikers van de ANDB dataset kunnen de gepubliceerde
gegevens op <https://druid.datalegend.net/andb> vinden.

* Inhoudsopgave

Dit repository bevat de volgende directories:

- [[doc][/doc]] :: Documentatie bestanden voor de ANDB dataset.
- [[img][/img]] :: Afbeeldingen die aspecten van de ANDB dataset toelichten.
- [[jsf][/jsf]] :: CoW scripts voor de transformatie van de ANDB dataset naar linked data.
- [[rdf][/rdf]] :: Statische RDF bestanden die deel uitmaken van de ANDB
  dataset.

* Installatie

Voer de volgende commando's uit om SHACL validatie over de voorbeeld dataset uit te voeren:

#+begin_src sh
cd src
npm install
node script.js
#+end_src
